language: java
jdk:
  - oraclejdk8

before_script:
  - git clone $TEST_PACKAGE tests
  - git clone $TEST test
  - ./setup.sh

script:
  - ./gradlew clean
  - ./gradlew build

notifications:
  webhooks:
    urls:
      - http://non.com/travisci
